In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cu124'

In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Using GPU: NVIDIA GeForce 940MX


## Tensor

In [5]:
## using empty
a = torch.empty(2, 3)
a

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31]])

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2, 3)

tensor([[0.0115, 0.9707, 0.1604],
        [0.7095, 0.8111, 0.6217]])

In [14]:
# use of seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# use of seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
# other ways

# arange
print("Using arange->", torch.arange(0, 10, 2))

# using linspace (linearly spaced)
print("Using linspace->", torch.linspace(1, 10, 10))

# using eye
print("Using eye->", torch.eye(5))

# using full
print("Using full->", torch.full((3, 3), 5))

Using arange-> tensor([0, 2, 4, 6, 8])
Using linspace-> tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [21]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape

torch.Size([2, 3])

In [23]:
torch.empty_like(x)

tensor([[    131076064390544,          1170287408,                   0],
        [                  0,                   0, 7310593858020254331]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [27]:
torch.rand_like(
    x
)  # because x is contains int not a float(long) and rand generates float number, it throws error, we have to mentione long data type

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [29]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

### Tensor Data Types

In [30]:
# find data type
x.dtype

torch.int64

In [31]:
# assigned data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [32]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [33]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical operations

1. Scalar Operation

In [34]:
x = torch.rand(2, 2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [35]:
# additiopn
print("Addition-> ", x + 2)
# subtraction
print("Subtraction-> ", x - 2)
# multiplication
print("Multiplication-> ", x * 2)
# division
print("Division-> ", x / 2)
# int division
x * 100
print("Int Division-> ", x // 2)
# mod
print("Mod-> ", x % 2)
# power
print("power-> ", x**2)

Addition->  tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
Subtraction->  tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
Multiplication->  tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
Division->  tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])
Int Division->  tensor([[0., 0.],
        [0., 0.]])
Mod->  tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])
power->  tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


2. Element wise operation

In [37]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])
tensor([[0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430]])


In [38]:
# additiopn
print("Addition-> ", a + b)
# subtraction
print("Subtraction-> ", a - b)
# multiplication
print("Multiplication-> ", a * b)
# division
print("Division-> ", a / b)
# mod
print("Mod-> ", a % b)
# power
print("power-> ", a**b)

Addition->  tensor([[0.9538, 1.3137, 0.5332],
        [0.2568, 1.6012, 1.0494]])
Subtraction->  tensor([[ 0.6280, -0.4667, -0.4994],
        [ 0.1850,  0.3059,  0.3634]])
Multiplication->  tensor([[0.1288, 0.3770, 0.0087],
        [0.0079, 0.6175, 0.2423]])
Division->  tensor([[4.8557, 0.4757, 0.0327],
        [6.1557, 1.4723, 2.0593]])
Mod->  tensor([[0.1394, 0.4235, 0.0169],
        [0.0056, 0.3059, 0.0204]])
power->  tensor([[0.9625, 0.4654, 0.1216],
        [0.9473, 0.9697, 0.8876]])


In [39]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [40]:
# abs
torch.absolute(c)

tensor([1, 2, 3, 4])

In [41]:
# negative
torch.negative(c)

tensor([-1,  2, -3,  4])

In [42]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [43]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [44]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [45]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Operations

In [48]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 7., 5.],
        [9., 8., 9.]])

In [49]:
# sum
print("sum", torch.sum(e))
# sum along columns
print("Sum along columns", torch.sum(e, dim=0))
# sum along rows
print("Sum along row", torch.sum(e, dim=1))

sum tensor(47.)
Sum along columns tensor([18., 15., 14.])
Sum along row tensor([21., 26.])


In [50]:
# median
torch.median(e)

tensor(8.)

In [51]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [52]:
# product
torch.prod(e)

tensor(204120.)

In [53]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [54]:
# variance
torch.var(e)

tensor(2.5667)

In [55]:
# argmax
torch.argmax(e)

tensor(0)

In [56]:
# argmin
torch.argmin(e)

tensor(2)

4. Matrix operations

In [57]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [58]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[120,  40],
        [125,  60]])

In [59]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [60]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7, 6],
        [9, 7],
        [2, 7]])

In [61]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [62]:
# determinant
torch.det(h)

tensor(84.)

In [63]:
# inverse
torch.inverse(h)

tensor([[-0.1786,  0.1786, -0.1429],
        [ 0.1071, -0.1071,  0.2857],
        [ 0.1905,  0.1429, -0.3810]])

5. Comparison operations

In [64]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)

tensor([[6, 4, 0],
        [8, 4, 7]])
tensor([[2, 3, 8],
        [5, 6, 2]])


In [65]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

6. Special functions

In [66]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 5., 0.],
        [4., 2., 7.]])

In [67]:
# log
torch.log(k)

tensor([[2.1972, 1.6094,   -inf],
        [1.3863, 0.6931, 1.9459]])

In [68]:
# exp
torch.exp(k)

tensor([[8.1031e+03, 1.4841e+02, 1.0000e+00],
        [5.4598e+01, 7.3891e+00, 1.0966e+03]])

In [69]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 2.2361, 0.0000],
        [2.0000, 1.4142, 2.6458]])

In [70]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9933, 0.5000],
        [0.9820, 0.8808, 0.9991]])

In [71]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9331e-01, 9.5257e-01, 9.1105e-04],
        [6.6929e-03, 4.7426e-02, 9.9909e-01]])

In [72]:
# relu
torch.relu(k)

tensor([[9., 5., 0.],
        [4., 2., 7.]])

7. Inplace Operations

In [73]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])
tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])


In [74]:
m.add_(n)
m

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [75]:
n

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [76]:
torch.relu(m)

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [77]:
m.relu_()

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

In [78]:
m

tensor([[0.4670, 0.6286, 1.1429],
        [1.1066, 0.4454, 0.7796]])

8. Copying a Tensor

In [79]:
a = torch.rand(2, 3)
a

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [80]:
b = a

In [81]:
b

tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [82]:
a[0][0] = 0

In [83]:
a

tensor([[0.0000, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [84]:
b

tensor([[0.0000, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [85]:
id(a)

131073914518688

In [86]:
id(b)

131073914518688

In [87]:
b = a.clone()

In [88]:
a

tensor([[0.0000, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [89]:
b

tensor([[0.0000, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [90]:
a[0][0] = 10

In [91]:
a

tensor([[10.0000,  0.5224,  0.4175],
        [ 0.0340,  0.9157,  0.3079]])

In [92]:
b

tensor([[0.0000, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])

In [93]:
id(a)

131073914518688

In [94]:
id(b)

131073914519088